### ISSUE TITLE
Should the socket be closed when it's finished?

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/ilp-protocol-paystream#1]
Should there be an option to keep it open but close it by default when it reaches the limit?

Should there be a way to communicate in the protocol that you're going to close the socket?

**Comment by emschwartz** [comment]
They should also time out from inactivity if the client just stops sending

**Comment by sharafian** [comment]
Even the timeout may not be sufficient if new state is being created on every query, because it means someone could use it to DoS SPSP endpoints. It would be nice if there were a stateless way to accept incoming funds like on the old PSK receiver, but it may not be possible here.

**Comment by emschwartz** [comment]
I don't think that makes sense, because this is dealing with something that is fundamentally stateful. It's tracking the balance, limits, maximum payment size, etc. I don't think it'll be that much overhead, but I think there will be some limit to the number of connections a server can have open.
