### ISSUE TITLE
Paying via several sockets to one invoice

### ISSUE THREAD

**Issue by sharafian** [emschwartz/ilp-protocol-paystream#10]
The simple logic would be to say that one socket corresponds to one invoice. But if an invoice is persistent and several people can pay to it, there should be no reason why there cannot be several sockets open and paying off one invoice.

It's not clear to me how best to manage the balance to accomplish this. Right now I'm just closing the channel when the invoice is filled, but that feels a little bit hacky. Another option would be to change the balance of all sockets related to an invoice whenever a packet comes in, but then it creates a ton of messages.

**Comment by emschwartz** [comment]
How likely is it that people will have sockets open at the same time? Is this really a use case we should design for?

We might be able to do something where it waits a bit after you change the limit before sending the request. That would give it time to accumulate multiple limit adjustments, or it might already get a packet from the other side and be able to communicate the new limits in that time.

**Comment by sharafian** [comment]
I suppose it's not super common, so maybe my slightly hacky fix will work.

We can just assume only one person is paying, and then if the invoice is filled unexpectedly early it can stop accepting payments and tell the sender that it's all done.

**Comment by emschwartz** [comment]
Can we close this issue now? I don't think we're going to support this in this module any time soon
