### ISSUE TITLE
Methods to wait for specific amount to be sent or received

### ISSUE THREAD

**Issue by emschwartz** [emschwartz/ilp-protocol-paystream#7]
Working with the `minBalance` and `maxBalance` directly can be a bit unintuitive. Should we add methods like `sendSourceAmount` that return a Promise that resolves when the amount has been sent, or `receiveAmount` that resolves when an amount has been received?

One thing to figure out with such methods is how to deal with the case where the balance is not already at a limit. If the `balance` is 0 and the `minBalance` is 100 and you call `receiveAmount(50)`, should it wait until the balance is 50 or 150? Also, what happens if you call one of these methods again before the first call has resolved? Should it add to (or subtract from) the limit and wait until the updated limit is reached?

**Comment by sharafian** [comment]
I think the most useful function would be to wait until the stream has stabilized. That way you can set a min/max, and then wait for it to reach the value that you specified.

**Comment by emschwartz** [comment]
Added `socket.stabilized()`.

Another idea for helper functions would be a way to open send-only or receive-only sockets that set the min/max balances automatically, try to connect and do their thing, and maybe close again when they're done (resolving a promise when they do).

**Comment by emschwartz** [comment]
I think we can close this for now since we have the `stabilized` method. We can discuss other helper functions later if they seem like they'd be useful
